name: Proto File Generation

on:
  workflow_run:
    workflows: ["Generate and Release"]
    types:
      - completed

jobs:
  generate-proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Specify the Python version
      
      - name: Install cantools
        run: python -m pip install cantools  # Install cantools library

      - name: Download dbc artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: dbcfile
          path: .
      
      - name: Download tag name artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: tag-name-artifact
      
      - name: Download upload_url artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: upload-url-artifact
        

      - name: Convert DBC to PROTO
        run: |
          python dbc_to_proto/dbc_to_proto.py dbcfile hytech.proto
        
      
      - name: Set tag_name from file
        run: |
            TAG_NAME=$(cat tag_name.txt)
            echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      - name: Set upload_url from file
        run: |
            UPLOAD_URL=$(cat upload_url.txt)
            echo "upload_url=$UPLOAD_URL" >> $GITHUB_ENV
    
      - name: Set up Protobuf tools and generate HTML file
        run: |
          mkdir -p docs
          mkdir -p proto/nanopb/google/protobuf
          
          sudo apt-get install -y --no-install-recommends protobuf-compiler
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@v1.5.1
          export PATH=$PATH:$HOME/go/bin
          
          curl -o proto/nanopb/google/protobuf/descriptor.proto https://raw.githubusercontent.com/nanopb/nanopb/nanopb-0.4.9.1/generator/proto/google/protobuf/descriptor.proto
          curl -o proto/nanopb/nanopb.proto https://raw.githubusercontent.com/nanopb/nanopb/nanopb-0.4.9.1/generator/proto/nanopb.proto
          protoc -I=./. -I=proto/nanopb --doc_out=./docs --doc_opt=html,${{ env.tag_name }}.html hytech.proto

      - name: Upload to existing release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TESTING_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ./docs/${{ env.tag_name }}.html
          asset_name: ${{ env.tag_name }}.html
          asset_content_type: text/plain